---
periodics:
  - name: ci-infra-prow-labelsync
    cron: "17 * * * *" # Every hour at 17 minutes past the hour
    cluster: prow
    decorate: true
    labels:
      app: label-sync
    extra_refs:
    - org: kcp-dev
      repo: infra
      base_ref: main
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
    spec:
      containers:
      - image: gcr.io/k8s-prow/label_sync:v20230523-2834e18241
        command:
        - label_sync
        args:
        - --config=/home/prow/go/src/github.com/kcp-dev/infra/prow/labels.yaml
        - --confirm=true
        - --only=kcp-dev/kcp,kcp-dev/api-syncagent,kcp-dev/kcp-operator,kcp-dev/multicluster-provider,kcp-dev/infra,kcp-dev/helm-charts,kcp-dev/kcp.io,kcp-dev/generic-controlplane,kcp-dev/client-go,kcp-dev/code-generator,kcp-dev/apimachinery,kcp-dev/controller-runtime,kcp-dev/logicalcluster,kcp-dev/publishing-bot
        - --token=/etc/oauth-token/token
        - --endpoint=http://ghproxy.prow.svc.cluster.local
        - --endpoint=https://api.github.com
        - --debug
        volumeMounts:
        - name: oauth-token
          mountPath: /etc/oauth-token
          readOnly: true
      volumes:
      - name: oauth-token
        secret:
          secretName: github-token
