presubmits:
  kcp-dev/infra:
    - name: pull-infra-validate-prow-yaml
      always_run: true
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20230919-a4926a4d02
            command:
              - checkconfig
            args:
              - -plugin-config=/home/prow/go/src/github.com/kcp-dev/infra/prow/plugins.yaml
              - -config-path=/home/prow/go/src/github.com/kcp-dev/infra/prow/config.yaml
              - -job-config-path=/home/prow/go/src/github.com/kcp-dev/infra/prow/jobs
              - -prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)

    - name: pull-infra-validate-prow-jobs
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      run_if_changed: "prow/jobs/"
      branches:
        - ^main$
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20230919-a4926a4d02
            command:
              - checkconfig
            args:
              - -plugin-config=/home/prow/go/src/github.com/kcp-dev/infra/prow/plugins.yaml
              - -config-path=/home/prow/go/src/github.com/kcp-dev/infra/prow/config.yaml
              - -job-config-path=/home/prow/go/src/github.com/kcp-dev/infra/prow/jobs
              - -strict

    - name: pull-infra-prow-labelsync
      cluster: prow
      labels:
        app: label-sync
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      run_if_changed: '^prow/labels.yaml$'
      spec:
        containers:
        - image: gcr.io/k8s-prow/label_sync:v20230523-2834e18241
          command:
          - label_sync
          args:
          - --config=/home/prow/go/src/github.com/kcp-dev/infra/prow/labels.yaml
          - --orgs=kcp-dev
          - --token=/etc/oauth-token/token
          - --endpoint=http://ghproxy.prow.svc.cluster.local
          - --endpoint=https://api.github.com
          - --debug
          volumeMounts:
          - name: oauth-token
            mountPath: /etc/oauth-token
            readOnly: true
        volumes:
        - name: oauth-token
          secret:
            secretName: github-token

    - name: pull-infra-images-build
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      # this forces to bump the image tag in this file to get a
      # new image build
      run_if_changed: '^images/build/env$'
      labels:
        preset-goproxy: "true"
      spec:
        containers:
          - image: quay.io/containers/buildah:v1.30.0
            command:
              - images/build/hack/build-image.sh
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
            env:
              - name: DRY_RUN
                value: '1'
            resources:
              requests:
                memory: 1Gi
                cpu: 1
