postsubmits:
  kcp-dev/infra:
    - name: post-infra-deploy-prow-cluster
      max_concurrency: 1
      run_if_changed: "clusters/prow/"
      decorate: true
      cluster: prow
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      labels:
        preset-prow-kubeconfig: "true"
      branches:
        - ^main$
      spec:
        containers:
          - image: quay.io/kubermatic/build:go-1.20-node-18-6
            command:
              - clusters/prow/hack/ci/deploy.sh
            env:
              - name: KUBECONFIG
                value: /etc/prow/kubeconfig/kubeconfig
              - name: KUBE_CONTEXT
                value: prow

    - name: post-infra-deploy-build-cluster
      max_concurrency: 1
      run_if_changed: "clusters/build/"
      decorate: true
      cluster: prow
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      labels:
        preset-prow-kubeconfig: "true"
      branches:
        - ^main$
      spec:
        containers:
          - image: quay.io/kubermatic/build:go-1.20-node-18-6
            command:
              - clusters/build/hack/ci/deploy.sh
            env:
              - name: KUBECONFIG
                value: /etc/prow/kubeconfig/kubeconfig
              - name: KUBE_CONTEXT
                value: default

    - name: post-infra-publish-images-1.23-build
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      cluster: prow # GHCR credentials are only available here
      labels:
        preset-ghcr-credentials: "true"
      branches:
        - ^main$
      run_if_changed: '^images/build/go-1.23'
      spec:
        containers:
          - image: quay.io/containers/buildah:v1.39.0
            command:
              - images/build/hack/build-image.sh
              - go-1.23
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 2
                memory: 3Gi

    - name: post-infra-publish-images-1.24-build
      decorate: true
      clone_uri: "ssh://git@github.com/kcp-dev/infra.git"
      cluster: prow # GHCR credentials are only available here
      labels:
        preset-ghcr-credentials: "true"
      branches:
        - ^main$
      run_if_changed: '^images/build/go-1.24'
      spec:
        containers:
          - image: quay.io/containers/buildah:v1.39.0
            command:
              - images/build/hack/build-image.sh
              - go-1.24
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 2
                memory: 3Gi
